### ISSUE TITLE
[bug] 代码运行出错！！急！急！非常感谢！

### ISSUE THREAD

**Issue by SXxinxiaosong** [Ablustrund/LoRAMoE#9]
代码修改：1. 将模型换成了llama3
![image](https://github.com/Ablustrund/LoRAMoE/assets/105906157/082097b5-49dc-4666-a50c-9632068e02e1)
2. 修改了device
![image](https://github.com/Ablustrund/LoRAMoE/assets/105906157/d7ab4e7d-353c-4aad-bb41-245683bc0fcd)

报错情况：Traceback (most recent call last):
  File "/home/xsong/SiameseModelTrain/LoRAMoE/run_loramoe.py", line 569, in <module>
    main()
  File "/home/xsong/SiameseModelTrain/LoRAMoE/run_loramoe.py", line 345, in main
    tokenizer = LlamaTokenizer.from_pretrained(model_args.tokenizer_name_or_path, **tokenizer_kwargs)
  File "/home/xsong/SiameseModelTrain/LoRAMoE/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "/home/xsong/SiameseModelTrain/LoRAMoE/transformers/tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/xsong/SiameseModelTrain/LoRAMoE/transformers/models/llama/tokenization_llama.py", line 96, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/sentencepiece/__init__.py", line 961, in Load
    return self.LoadFromFile(model_file)
  File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/sentencepiece/__init__.py", line 316, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1415452) of binary: /home/xsong/anaconda3/envs/newloramoe/bin/python
Traceback (most recent call last):
  File "/home/xsong/anaconda3/envs/newloramoe/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_loramoe.py FAILED
报错情况：Traceback (most recent call last):
  File "/home/xsong/SiameseModelTrain/LoRAMoE/run_loramoe.py", line 569, in <module>
    main()
  File "/home/xsong/SiameseModelTrain/LoRAMoE/run_loramoe.py", line 345, in main
    tokenizer = LlamaTokenizer.from_pretrained(model_args.tokenizer_name_or_path, **tokenizer_kwargs)
  File "/home/xsong/SiameseModelTrain/LoRAMoE/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "/home/xsong/SiameseModelTrain/LoRAMoE/transformers/tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/xsong/SiameseModelTrain/LoRAMoE/transformers/models/llama/tokenization_llama.py", line 96, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/sentencepiece/__init__.py", line 961, in Load
    return self.LoadFromFile(model_file)
  File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/sentencepiece/__init__.py", line 316, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1415452) of binary: /home/xsong/anaconda3/envs/newloramoe/bin/python
Traceback (most recent call last):
  File "/home/xsong/anaconda3/envs/newloramoe/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_loramoe.py FAILED

**Comment by Ablustrund** [comment]
请检查是否正确加载我们修改的transformers。如果选择使用更高版本的torch和transformers，请将我们修改的部分（主要为llama_modeling.py）适配到最新版本的transformers即可。

**Comment by SXxinxiaosong** [comment]
请问Cuda改成11.7是不能正确运行嘛


---- 回复的原邮件 ----
| 发件人 | Shihan ***@***.***> |
| 发送日期 | 2024年05月18日 16:23 |
| 收件人 | Ablustrund/LoRAMoE ***@***.***> |
| 抄送人 | xxs ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Ablustrund/LoRAMoE] [bug] 代码运行出错！！急！急！非常感谢！ (Issue #9) |

请检查是否正确加载我们修改的transformers。如果选择使用更高版本的torch和transformers，请将我们修改的部分（主要为llama_modeling.py）适配到最新版本的transformers即可。

**Comment by SXxinxiaosong** [comment]
改成一张卡之后 好像会存在多卡通讯问题

---- 回复的原邮件 ----
| 发件人 | Shihan ***@***.***> |
| 发送日期 | 2024年05月18日 16:23 |
| 收件人 | Ablustrund/LoRAMoE ***@***.***> |
| 抄送人 | xxs ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Ablustrund/LoRAMoE] [bug] 代码运行出错！！急！急！非常感谢！ (Issue #9) |

请检查是否正确加载我们修改的transformers。如果选择使用更高版本的torch和transformers，请将我们修改的部分（主要为llama_modeling.py）适配到最新版本的transformers即可。

**Comment by SXxinxiaosong** [comment]
还请问 torch用2.0.1可以吗 感谢



---- 回复的原邮件 ----
| 发件人 | Shihan ***@***.***> |
| 日期 | 2024年05月18日 16:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Ablustrund/LoRAMoE] [bug] 代码运行出错！！急！急！非常感谢！ (Issue #9) |

请检查是否正确加载我们修改的transformers。如果选择使用更高版本的torch和transformers，请将我们修改的部分（主要为llama_modeling.py）适配到最新版本的transformers即可。

**Comment by Liukairong2023** [comment]
> 代码修改：1. 将模型换成了llama3 ![image](https://private-user-images.githubusercontent.com/105906157/331592081-082097b5-49dc-4666-a50c-9632068e02e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MTQyNDQsIm5iZiI6MTcxNzkxMzk0NCwicGF0aCI6Ii8xMDU5MDYxNTcvMzMxNTkyMDgxLTA4MjA5N2I1LTQ5ZGMtNDY2Ni1hNTBjLTk2MzIwNjhlMDJlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwNjE5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTk0MmI4NmNmYjlhMWM5ODQ3YjlhYzQyMTM3OGRhZTNkNjJiMTg5ZjljN2I2NjMzMmNkNTg1MTZmMDk4NmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7gXUQ5bU2VlmNPvNbuYMO0PlY6OpUTpIEXzqV3A6M5A) 2. 修改了device ![image](https://private-user-images.githubusercontent.com/105906157/331592247-d7ab4e7d-353c-4aad-bb41-245683bc0fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MTQyNDQsIm5iZiI6MTcxNzkxMzk0NCwicGF0aCI6Ii8xMDU5MDYxNTcvMzMxNTkyMjQ3LWQ3YWI0ZTdkLTM1M2MtNGFhZC1iYjQxLTI0NTY4M2JjMGZjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwNjE5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTkzOGU3MjQ2NTgxNDM4ZWJiN2JiNDgwNGI5YmZmOWQwNDk4MDFjNTgwOWYzZWJlYWJhOTFmMDNlZWMyYWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.stMdpdrerb5HtdYJMM2IELIfaCj_yV2Mw6wMwAi6XpM)
> 
> # 报错情况：Traceback (most recent call last):
> File "/home/xsong/SiameseModelTrain/LoRAMoE/run_loramoe.py", line 569, in
> main()
> File "/home/xsong/SiameseModelTrain/LoRAMoE/run_loramoe.py", line 345, in main
> tokenizer = LlamaTokenizer.from_pretrained(model_args.tokenizer_name_or_path, **tokenizer_kwargs)
> File "/home/xsong/SiameseModelTrain/LoRAMoE/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
> return cls._from_pretrained(
> File "/home/xsong/SiameseModelTrain/LoRAMoE/transformers/tokenization_utils_base.py", line 1988, in _from_pretrained
> tokenizer = cls(*init_inputs, **init_kwargs)
> File "/home/xsong/SiameseModelTrain/LoRAMoE/transformers/models/llama/tokenization_llama.py", line 96, in **init**
> self.sp_model.Load(vocab_file)
> File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/sentencepiece/**init**.py", line 961, in Load
> return self.LoadFromFile(model_file)
> File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/sentencepiece/**init**.py", line 316, in LoadFromFile
> return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
> TypeError: not a string
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1415452) of binary: /home/xsong/anaconda3/envs/newloramoe/bin/python
> Traceback (most recent call last):
> File "/home/xsong/anaconda3/envs/newloramoe/bin/torchrun", line 33, in
> sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
> File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/**init**.py", line 346, in wrapper
> return f(*args, **kwargs)
> File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
> run(args)
> File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
> elastic_launch(
> File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in **call**
> return launch_agent(self._config, self._entrypoint, list(args))
> File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
> raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> # run_loramoe.py FAILED
> 报错情况：Traceback (most recent call last):
> File "/home/xsong/SiameseModelTrain/LoRAMoE/run_loramoe.py", line 569, in
> main()
> File "/home/xsong/SiameseModelTrain/LoRAMoE/run_loramoe.py", line 345, in main
> tokenizer = LlamaTokenizer.from_pretrained(model_args.tokenizer_name_or_path, **tokenizer_kwargs)
> File "/home/xsong/SiameseModelTrain/LoRAMoE/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
> return cls._from_pretrained(
> File "/home/xsong/SiameseModelTrain/LoRAMoE/transformers/tokenization_utils_base.py", line 1988, in _from_pretrained
> tokenizer = cls(*init_inputs, **init_kwargs)
> File "/home/xsong/SiameseModelTrain/LoRAMoE/transformers/models/llama/tokenization_llama.py", line 96, in **init**
> self.sp_model.Load(vocab_file)
> File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/sentencepiece/**init**.py", line 961, in Load
> return self.LoadFromFile(model_file)
> File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/sentencepiece/**init**.py", line 316, in LoadFromFile
> return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
> TypeError: not a string
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1415452) of binary: /home/xsong/anaconda3/envs/newloramoe/bin/python
> Traceback (most recent call last):
> File "/home/xsong/anaconda3/envs/newloramoe/bin/torchrun", line 33, in
> sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
> File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/**init**.py", line 346, in wrapper
> return f(*args, **kwargs)
> File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
> run(args)
> File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
> elastic_launch(
> File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in **call**
> return launch_agent(self._config, self._entrypoint, list(args))
> File "/home/xsong/anaconda3/envs/newloramoe/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
> raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> run_loramoe.py FAILED

问题解决了嘛
